### PR TITLE
Update zh_cn.lang

### PR DESCRIPTION
**Pull request by MJQFHCMZ**
An update for zh_cn.lang.

### CODE REVIEW

**Comment by MJQFHCMZ** [comment]
I think it's better for a mod translator to try translating a material that can only be transliterated phonetically based on its idiosyncrasies, and furthermore, until you can confirm exactly what a translation key that contains a hardcoded key is supposed to say, use the original hardcoded code to make sure you don't get it too wrong!

**Comment by MJQFHCMZ** [comment]
I think it's better for a mod translator to try translating a material that can only be transliterated phonetically based on its idiosyncrasies, and furthermore, until you can confirm exactly what a translation key that contains a hardcoded key is supposed to say, use the original hardcoded code to make sure you don't get it too wrong!

**Comment by MJQFHCMZ** [comment]
I've changed the translation names of two materials that are still untranslated in the current version.

    Sanguiseelium→汲血魂金
    Zracohlium→临界辐金

Tools made with Sanguiseelium have modifiers "leeching" and "soulforged", so I translate them as "blood-drawing soul gold"（汲血魂金）, and tools made with Zracohlium have modifiers "supercritical" and "helpful_radiation", so I translate them as "critical irradiation gold"（临界辐金）.

**Comment by MJQFHCMZ** [comment]
Since the translations of the material "XXX" are inconsistent across translators, I've translated this material as Void (it's an alloy that doesn't lend itself to too long a name).

    ioxite→虚空

Also: I translated the new material modifiers as well (albeit machine translated).

**Comment by MJQFHCMZ** [comment]
Since the translations of the material "ioximite" are inconsistent across translators, I've translated this material as Void（虚空） (it's an alloy that doesn't lend itself to too long a name).

    ioximite→虚空合金

Also: I translated the new material modifiers as well (albeit machine translated).

**Comment by DabbingEevee** [comment]
Since ioximite isn't a metal, I'm not sure I like "合金". 

Also would you mind merging this to the dev branch instead?

**Comment by MJQFHCMZ** [comment]
I just went back into the game and re-checked, and "ioximite" is technically a composite crystal, so that was my mistake!
This branch is just for uploading my own localization, if you want to merge it into Dev, that would be great!

**Comment by DabbingEevee** [comment]
perfect ty

**Pull request merged**
